name: Deploy to yejin
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy by SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd Pialmot
            git pull
            cd Front/Pialmot/
            npm i
            npm run build
            cd ../../Back/Server/
            npm i
            tsc
            if pm2 list | grep -q 'index'; then pm2 reload index.js; else pm2 start index.js; fi
            if pm2 list | grep -q 'multi'; then pm2 reload multi.js; else pm2 start multi.js; fi
