name: Deploy to yejin
on:
  push:
    branches:
    - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy by SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd Pialmot
          git pull
          cd Front/Pialmot/
          npm i
          npm run build
          cd ../../Back/Server/
          npm i
          tsc
          echo ${{ secrets.PASSWORD }} | sudo -S pm2 restart 0
